version: '3.3'
services:
  master:
    build: ./jmeter-master
    hostname: master
    tty: true
    networks:
      - jmeter
    volumes:
      - ./jmx_scripts:/home
  slave:
    build: ./jmeter-slave
    tty: true
    networks:
      - jmeter
    volumes:
      - ./jmx_scripts:/home
  slave2:
    build: ./jmeter-slave
    tty: true
    networks:
      - jmeter
    volumes:
      - ./jmx_scripts:/home
  
networks:
  jmeter:
    driver: bridge